name: ace-ml-models
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - matplotlib=*
  - pandas=2.2.3
  - scikit-learn=*
  - snowflake-ml-python=*
  - snowflake-snowpark-python=*
  - xgboost=*